### ISSUE TITLE
Android 13 MissingPluginException (No implementation found for method login on channel flutter_naver_login)

### ISSUE THREAD

**Issue by andynvt** [yoonjaepark/flutter_naver_login#88]
Device info: Samsung galaxy note20 - android 13

![CleanShot 2023-03-01 at 11 07 46](https://user-images.githubusercontent.com/26719596/222042567-fd10bbbe-e4b4-4251-bb15-102e68dafdc5.png)

```
{id: TP1A.220624.014, host: 21DK7906, tags: release-keys, type: user, model: SM-N980F, board: exynos990, brand: samsung, device: c1s, product: c1sxx, display: TP1A.220624.014.N980FXXS5GWB1, hardware: exynos990, bootloader: N980FXXS5GWB1, version: {baseOS: samsung/c1sxx/c1s:13/TP1A.220624.014/N980FXXU5GVJE:user/release-keys, sdkInt: 33, release: 13, codename: REL, incremental: N980FXXS5GWB1, previewSdkInt: 0, securityPatch: 2023-02-01}, fingerprint: samsung/c1sxx/c1s:13/TP1A.220624.014/N980FXXS5GWB1:user/release-keys, manufacturer: samsung, supportedAbis: [arm64-v8a, armeabi-v7a, armeabi], systemFeatures: [android.hardware.sensor.proximity, com.samsung.android.sdk.camera.processor, com.samsung.feature.aodservice_v10, com.sec.feature.motionrecognition_service, com.sec.feature.cover.sview, android.hardware.telephony.ims.singlereg, android.hardware.sensor.accelerometer, android.software.controls, android.hardware.faketouch, android.software.telecom, com.samsung.feature.audio_listenback, android.hardware.telephony.euicc, android.hardware.usb.accessory, android.software.backup, android.hardware.touchscreen, android.hardware.touchscreen.multitouch, android.software.print, android.software.activities_on_secondary_displays, com.sec.feature.nfc_authentication_cover, android.hardware.wifi.rtt, com.samsung.feature.SAMSUNG_EXPERIENCE, com.google.android.feature.ACCESSIBILITY_PRELOAD, com.sec.feature.nfc_authentication, android.software.voice_recognizers, android.software.picture_in_picture, android.hardware.fingerprint, com.samsung.android.knox.knoxsdk, android.hardware.sensor.gyroscope, android.hardware.audio.low_latency, android.software.vulkan.deqp.level, android.software.cant_save_state, android.hardware.security.model.compatible, com.samsung.feature.device_category_phone, com.samsung.android.nfc.t4temul, android.hardware.opengles.aep, com.sec.feature.sensorhub, android.hardware.bluetooth, android.software.window_magnification, android.hardware.camera.autofocus, android.hardware.telephony.gsm, android.hardware.telephony.ims, com.sec.feature.cocktailpanel, android.software.sip.voip, android.hardware.se.omapi.ese, com.sec.feature.saccessorymanager, com.samsung.feature.samsung_experience_mobile, com.samsung.android.camerasdkservice, android.hardware.camera.concurrent, android.hardware.usb.host, android.hardware.audio.output, android.software.verified_boot, android.hardware.camera.flash, android.hardware.camera.front, android.hardware.sensor.hifi_sensors, android.hardware.se.omapi.uicc, android.hardware.strongbox_keystore, android.hardware.screen.portrait, com.google.android.feature.ASI, android.hardware.nfc, com.google.android.feature.TURBO_PRELOAD, com.samsung.feature.ipsgeofence, com.nxp.mifare, android.hardware.sensor.stepdetector, android.software.home_screen, com.sec.feature.cover.ledbackcover, android.hardware.microphone, com.samsung.feature.aremoji.v2, android.software.autofill, com.samsung.android.sdk.camera.processor.effect, android.software.securely_removes_users, android.hardware.bluetooth_le, android.hardware.sensor.compass, android.hardware.touchscreen.multitouch.jazzhand, android.hardware.sensor.barometer, android.software.app_widgets, android.software.input_methods, android.hardware.sensor.light, android.hardware.vulkan.version, android.software.companion_device_setup, com.samsung.feature.galaxyfinder_v7, com.sec.feature.wirelesscharger_authentication, android.software.device_admin, android.hardware.keystore.limited_use_key, android.hardware.wifi.passpoint, android.hardware.camera, android.hardware.screen.landscape, android.hardware.ram.normal, com.samsung.feature.samsungpositioning.snlp, com.samsung.android.authfw, com.samsung.android.api.version.2402, com.samsung.android.api.version.2403, com.samsung.android.api.version.2501, com.samsung.android.api.version.2502, com.samsung.android.api.version.2601, com.samsung.android.api.version.2701, com.samsung.android.api.version.2801, com.samsung.android.api.version.2802, com.samsung.android.api.version.2803, com.samsung.android.api.version.2901, com.samsung.android.api.version.2902, com.samsung.android.api.version.2903, com.samsung.android.api.version.3001, com.samsung.android.api.version.3002, com.samsung.android.api.version.3101, com.samsung.android.api.version.3201, com.samsung.android.api.version.3301, com.sec.feature.cover, android.software.managed_users, com.sec.feature.nsflp, android.software.webview, android.hardware.sensor.stepcounter, android.hardware.camera.capability.manual_post_processing, com.sec.feature.spen_usp, android.hardware.camera.any, android.hardware.camera.capability.raw, android.hardware.vulkan.compute, android.software.connectionservice, android.hardware.touchscreen.multitouch.distinct, android.hardware.location.network, com.sec.android.secimaging, android.software.cts, android.software.sip, android.hardware.camera.capability.manual_sensor, android.software.app_enumeration, android.hardware.camera.level.full, com.sec.feature.cover.clearsideviewcover, com.sec.feature.usb_authentication, android.hardware.wifi.direct, android.software.live_wallpaper, android.software.ipsec_tunnels, android.software.freeform_window_management, android.hardware.nfc.hcef, android.hardware.nfc.uicc, android.hardware.location.gps, android.software.midi, com.samsung.feature.samsungpositioning, android.hardware.nfc.any, android.hardware.nfc.ese, android.hardware.nfc.hce, android.hardware.hardware_keystore, com.sec.feature.pocketsensitivitymode, android.hardware.wifi, android.hardware.location, android.hardware.vulkan.level, com.sec.feature.cover.flip, com.samsung.android.cameraxservice, com.samsung.android.knox.knoxsdk.api.level.33, com.samsung.android.knox.knoxsdk.api.level.34, com.samsung.android.knox.knoxsdk.api.level.35, com.samsung.android.knox.knoxsdk.api.level.36, android.hardware.wifi.aware, android.software.secure_lock_screen, android.hardware.biometrics.face, com.sec.feature.cover.nfcledcover, android.hardware.telephony, com.sec.android.smartface.smart_stay, android.software.file_based_encryption, null], isPhysicalDevice: true, supported32BitAbis: [armeabi-v7a, armeabi], supported64BitAbis: [arm64-v8a]}
```

Flutter doctor -v

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.8 on channel stable at /Users/leclevietnam/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (4 months ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/leclevietnam/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by LecleHuongTran** [comment]
Same issue, please help to check this. Thank you!

**Comment by peonani-jj** [comment]
I'd had the same problem, yet it was solved after I changed `FlutterActivity` to `FlutterFragmentActivity`.

```kotlin
// android/app/src/main/kotlin/com/example/{your-package-name}/MainActivity.kt
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```

**Comment by weenhoon** [comment]
> I'd had the same problem, yet it was solved after I changed `FlutterActivity` to `FlutterFragmentActivity`.
> 
> ```kotlin
> // android/app/src/main/kotlin/com/example/{your-package-name}/MainActivity.kt
> import io.flutter.embedding.android.FlutterFragmentActivity
> 
> class MainActivity: FlutterFragmentActivity() {
> }
> ```

Thanks for your help, I try with this but still can't fix it.

**Comment by peonani-jj** [comment]
You can upgrade NAVER login Android SDK from 5.2.0 to 5.4.0 manually.
[Guidelines - Korean](https://github.com/naver/naveridlogin-sdk-android/wiki/v5.3.0-%EC%9D%B4%EC%83%81-%EA%B0%80%EC%9D%B4%EB%93%9C-(%EC%B5%9C%EC%8B%A0-v5.4.0)#32-gradle-%EC%97%90%EC%84%9C-%EC%84%A4%EC%A0%95)
Yet I'm not sure this could be a solution for this problem.

**Comment by edhjs** [comment]
I have same issue. it works in debug mode and in installed version with apk, but has same problem in release mode uploaded to google play.

**Comment by byungjuJin** [comment]
check below out.

https://github.com/yoonjaepark/flutter_naver_login/issues/79#issuecomment-2921267899
